pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - author=paoloboni
      - title~=^Update\s.*
      - "status-success=test (adopt@1.8, 2.12.18)"
      - "status-success=test (adopt@1.8, 2.13.11)"
      - "status-success=test (adopt@1.8, 3.3.1)"
      - "status-success=test (openjdk@1.11, 2.12.18)"
      - "status-success=test (openjdk@1.11, 2.13.11)"
      - "status-success=test (openjdk@1.11, 3.3.1)"
      - "status-success=test (openjdk@1.17, 2.12.18)"
      - "status-success=test (openjdk@1.17, 2.13.11)"
      - "status-success=test (openjdk@1.17, 3.3.1)"
    actions:
      merge:
        method: squash
