language: scala

jdk:
  - openjdk8
  - openjdk11

scala:
  - 2.11.12
  - 2.12.13
  - 2.13.5

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
