language: scala

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11

scala:
  - 2.11.12
  - 2.12.12
  - 2.13.4

script:
  - sbt ++$TRAVIS_SCALA_VERSION scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck test

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
