addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.4.3")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "2.1.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.9.10")
addSbtPlugin("de.heikoseeberger" % "sbt-header"   % "5.6.0")
addSbtPlugin("com.github.sbt" % "sbt-release"  % "1.0.15")
//addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "1.8.2")
