addSbtPlugin("org.scalameta"     % "sbt-scalafmt"  % "2.5.2")
addSbtPlugin("com.github.sbt"    % "sbt-pgp"       % "2.2.1")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"  % "3.10.0")
addSbtPlugin("de.heikoseeberger" % "sbt-header"    % "5.10.0")
addSbtPlugin("com.github.sbt"    % "sbt-release"   % "1.3.0")
addSbtPlugin("org.typelevel"     % "sbt-tpolecat"  % "0.5.0")
addSbtPlugin("org.scoverage"     % "sbt-scoverage" % "2.0.9")
