---
name: CI
on:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'project/**'
      - '**.sbt'
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'project/**'
      - '**.sbt'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
        scala:
          - 2.12.14
          - 2.13.6
          - 3.0.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        uses: olafurpg/setup-scala@v10
        with:
          java-version: "adopt@1.${{ matrix.java }}"
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build and test
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck coverage test coverageReport
        shell: bash
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
