---
name: CI
on:
  pull_request:
    paths:
      - 'src/**'
      - 'project/**'
      - '**/*.sbt'
      - '.github/workflows/ci.yml'
  push:
    paths:
      - 'src/**'
      - 'project/**'
      - '**/*.sbt'
      - '.github/workflows/ci.yml'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java:
          - "adopt@1.8"
          - "openjdk@1.11"
          - "openjdk@1.17"
        scala:
          - 2.12.15
          - 2.13.8
          - 3.1.1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: olafurpg/setup-scala@v11 
        with:
          java-version: "${{ matrix.java }}"
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build and test
#        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck coverage test coverageReport
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck test
        shell: bash
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          fail_ci_if_error: true
