---
name: CI
on:
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - 'project/**'
      - '**/*.sbt'
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'project/**'
      - '**/*.sbt'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        java:
          - 8
          - 11
          - 17
        scala:
          - 2.12.15
          - 2.13.7
          - 3.1.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-scala@v2
        with:
          distribution: 'temurin'
          java-version: "${{ matrix.java }}"
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Build and test
#        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck coverage test coverageReport
        run: sbt ++${{ matrix.scala }} scalafmtCheckAll scalafmtSbtCheck headerCheck test:headerCheck test
        shell: bash
#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v1
#        with:
#          fail_ci_if_error: true
